# Generated by Django 5.2.2 on 2025-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0005_remove_customerregister_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregister',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
