# Generated by Django 5.2.2 on 2025-06-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0006_alter_customerregister_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('pan_status', models.IntegerField(default=0)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('adhaar_status', models.IntegerField(default=0)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_status', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.customerregister')),
            ],
        ),
    ]
