# Generated by Django 5.2.2 on 2025-06-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0014_alter_kycdetails_status_customermoredetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='mandal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
