# Generated by Django 5.2.2 on 2025-06-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0016_customerregister_kyc_accept_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='aadhar_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='pan_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
