# Generated by Django 5.2.2 on 2025-06-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0018_alter_kycdetails_aadhar_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoomineeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('address_proof_path', models.CharField(blank=True, max_length=250, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proof_path', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.customerregister')),
            ],
        ),
    ]
