# Generated by Django 5.2.2 on 2025-06-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0022_alter_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregister',
            name='payment_accept_status',
            field=models.IntegerField(default=0),
        ),
    ]
