# Generated by Django 5.2.2 on 2025-07-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0038_nomineedetails_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdetails',
            old_name='bank_account_number',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='kycdetails',
            old_name='bank_name',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='kycdetails',
            old_name='bank_task_id',
            new_name='bank_task_id',
        ),
    ]
