# Generated by Django 5.2.2 on 2025-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='drone_model_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
