# Generated by Django 5.2.2 on 2025-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0002_alter_customerregister_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregister',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
