# Generated by Django 5.2.2 on 2025-08-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0002_invoicedetails_drone_model_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nomineedetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgreementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_no', models.CharField(max_length=100)),
                ('agreement_date', models.DateField()),
                ('agreement_day', models.CharField(max_length=50)),
                ('agreement_month', models.CharField(max_length=50)),
                ('agreement_year_full', models.IntegerField()),
                ('agreement_year_short', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('drone_name', models.CharField(max_length=100)),
                ('drone_unique_code', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('witness_leassor', models.CharField(max_length=100)),
                ('witness_lessee', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.customerregister')),
                ('customer_more', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.customermoredetails')),
            ],
        ),
        migrations.CreateModel(
            name='DroneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(default=0)),
                ('accept_status', models.IntegerField(default=0)),
                ('requested_on', models.DateTimeField(blank=True, null=True)),
                ('accepted_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin')),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.agreementdetails')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.customerregister')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.role')),
            ],
        ),
    ]
