# Generated by Django 5.2.2 on 2025-07-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0002_invoicedetails_drone_model_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_no', models.CharField(max_length=100, unique=True)),
                ('agreement_date', models.DateField()),
                ('agreement_day', models.CharField(max_length=10)),
                ('agreement_month', models.CharField(max_length=20)),
                ('agreement_year_full', models.IntegerField()),
                ('agreement_year_short', models.CharField(max_length=2)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('drone_name', models.CharField(max_length=100)),
                ('drone_unique_code', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('witness_leassor', models.CharField(max_length=100)),
                ('witness_lessee', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.customerregister')),
                ('customer_more', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.customermoredetails')),
            ],
        ),
    ]
