# Generated by Django 5.2.2 on 2025-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0003_alter_customerregister_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregister',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
