# Generated by Django 5.2.2 on 2025-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0005_alter_agreementdetails_agreement_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementdetails',
            name='agreement_day',
            field=models.CharField(max_length=15),
        ),
    ]
