# Generated by Django 5.2.2 on 2025-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0006_alter_agreementdetails_agreement_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementdetails',
            name='agreement_day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agreementdetails',
            name='agreement_month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agreementdetails',
            name='agreement_year_short',
            field=models.CharField(max_length=50),
        ),
    ]
