# Generated by Django 5.2.2 on 2025-07-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0007_alter_agreementdetails_agreement_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementdetails',
            name='pdf_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
