# Generated by Django 5.2.2 on 2025-06-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0008_kycdetails_pan_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='pan_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='pan_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='pan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='pan_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
