# Generated by Django 5.2.2 on 2025-07-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0008_agreementdetails_pdf_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreementdetails',
            old_name='pdf_path',
            new_name='agreement_pdf_url',
        ),
    ]
