# Generated by Django 5.2.2 on 2025-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0009_rename_pdf_path_agreementdetails_agreement_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nomineedetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
