# Generated by Django 5.2.2 on 2025-08-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0010_customermoredetails_guardian_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementdetails',
            name='agreement_pdf_url',
        ),
        migrations.CreateModel(
            name='DroneOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(default=0)),
                ('accept_status', models.IntegerField(default=0)),
                ('requested_on', models.DateTimeField(blank=True, null=True)),
                ('accepted_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin')),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.agreementdetails')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.customerregister')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.role')),
            ],
        ),
    ]
