# Generated by Django 5.2.2 on 2025-08-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0011_remove_agreementdetails_agreement_pdf_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneoperation',
            name='drone_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.companydronemodelinfo'),
        ),
    ]
