# Generated by Django 5.2.2 on 2025-08-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0013_alter_droneoperation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneoperation',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin'),
        ),
    ]
