# Generated by Django 5.2.2 on 2025-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0017_kycdetails_aadhar_path_kycdetails_pan_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetails',
            name='aadhar_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kycdetails',
            name='pan_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
