# Generated by Django 5.2.2 on 2025-06-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0024_remove_admin_password_admin_changed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.role'),
        ),
        migrations.AddField(
            model_name='customerregister',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.role'),
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.role'),
        ),
        migrations.AddField(
            model_name='nomineedetails',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.role'),
        ),
    ]
