# Generated by Django 5.2.2 on 2025-06-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0029_nomineedetails_nominee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='selfie_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='signature_status',
            field=models.IntegerField(default=0),
        ),
    ]
