# Generated by Django 5.2.2 on 2025-06-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0031_paymentdetails_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='mobile_no',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customerregister',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerregister',
            name='mobile_no',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='role',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='mobile_no',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
