# Generated by Django 5.2.2 on 2025-06-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0034_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nomineedetails',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
