# Generated by Django 5.2.2 on 2025-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0042_paymentdetails_drone_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_type',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
