# Generated by Django 5.2.2 on 2025-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0043_paymentdetails_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_mode',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
