# Generated by Django 5.2.2 on 2025-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0044_alter_paymentdetails_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
