# Generated by Django 5.2.2 on 2025-07-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0048_merge_20250710_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='present_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='present_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='present_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='present_mandal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='present_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='present_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='same_address',
            field=models.BooleanField(default=False),
        ),
    ]
