# Generated by Django 5.2.2 on 2025-06-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(default='', max_length=15)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_send_type', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_on', models.DateTimeField(blank=True, null=True)),
                ('register_type', models.CharField(default='mannual_acc', max_length=20)),
                ('register_status', models.IntegerField(default=0)),
                ('account_status', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
