# Generated by Django 5.2.2 on 2025-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0004_alter_customerregister_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerregister',
            name='password',
        ),
        migrations.AlterField(
            model_name='customerregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
