# Generated by Django 5.2.2 on 2025-06-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0007_kycdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='pan_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
