# Generated by Django 5.2.2 on 2025-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0011_kycdetails_aadhaar_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdetails',
            old_name='adhaar_status',
            new_name='aadhar_status',
        ),
        migrations.RenameField(
            model_name='kycdetails',
            old_name='aadhaar_task_id',
            new_name='aadhar_task_id',
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='idfy_aadhar_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
