# Generated by Django 5.2.2 on 2025-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0012_rename_adhaar_status_kycdetails_aadhar_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='banck_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='idfy_bank_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
