# Generated by Django 5.2.2 on 2025-06-14 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0013_kycdetails_banck_task_id_kycdetails_idfy_bank_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetails',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CustomerMoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.customerregister')),
            ],
        ),
    ]
