# Generated by Django 5.2.2 on 2025-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0015_customermoredetails_city_customermoredetails_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregister',
            name='kyc_accept_status',
            field=models.IntegerField(default=0),
        ),
    ]
