# Generated by Django 5.2.2 on 2025-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0019_noomineedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='NoomineeDetails',
            new_name='NomineeDetails',
        ),
    ]
