# Generated by Django 5.2.2 on 2025-06-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0020_admin_rename_noomineedetails_nomineedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin'),
        ),
        migrations.AddField(
            model_name='customerregister',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin'),
        ),
        migrations.AddField(
            model_name='kycdetails',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin'),
        ),
        migrations.AddField(
            model_name='nomineedetails',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin'),
        ),
    ]
