# Generated by Django 5.2.2 on 2025-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0021_customermoredetails_admin_customerregister_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
