# Generated by Django 5.2.2 on 2025-06-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0030_customermoredetails_selfie_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='part_number',
            field=models.IntegerField(default=1),
        ),
    ]
