# Generated by Django 5.2.2 on 2025-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0032_alter_admin_email_alter_admin_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
