# Generated by Django 5.2.2 on 2025-06-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0035_customermoredetails_status_nomineedetails_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
