# Generated by Django 5.2.2 on 2025-06-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0037_paymentdetails_drone_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineedetails',
            name='share',
            field=models.FloatField(default=0.0),
        ),
    ]
