# Generated by Django 5.2.2 on 2025-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0039_rename_banck_account_number_kycdetails_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='aadhar_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
