# Generated by Django 5.2.2 on 2025-07-09 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0039_rename_banck_account_number_kycdetails_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDroneModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Pavaman Aviation Private Limited', max_length=150)),
                ('model_name', models.CharField(default='TEJAS', max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('uin_number', models.CharField(max_length=100)),
                ('date_of_model', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('assign_status', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin')),
            ],
        ),
    ]
