# Generated by Django 5.2.2 on 2025-07-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0040_kycdetails_aadhar_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
