# Generated by Django 5.2.2 on 2025-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0041_paymentdetails_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='drone_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
