# Generated by Django 5.2.2 on 2025-07-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0045_paymentdetails_installment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='amount',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
