# Generated by Django 5.2.2 on 2025-07-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0046_remove_paymentdetails_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='installment_amount',
            new_name='amount',
        ),
    ]
