# Generated by Django 5.2.2 on 2025-07-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0040_companydronemodelinfo'),
        ('invest_app', '0047_rename_installment_amount_paymentdetails_amount'),
    ]

    operations = [
    ]
