# Generated by Django 5.2.2 on 2025-07-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0049_customermoredetails_present_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('uin_no', models.CharField(blank=True, max_length=100, null=True)),
                ('parts_quantity', models.IntegerField(default=1)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_invoice_amount_words', models.CharField(default='', max_length=255)),
                ('address_type', models.CharField(choices=[('permanent', 'Permanent Address'), ('present', 'Present Address')], default='permanent', max_length=10)),
                ('description', models.TextField(default='TEJA-S (UIN Drone)', max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.admin')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest_app.customerregister')),
                ('drone_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.companydronemodelinfo')),
            ],
        ),
    ]
