# Generated by Django 5.2.2 on 2025-07-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0050_invoicedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetails',
            name='invoice_date',
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='customer_more',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.customermoredetails'),
        ),
    ]
