# Generated by Django 5.2.2 on 2025-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0051_remove_invoicedetails_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice_type',
            field=models.CharField(choices=[('drone', 'Drone'), ('accessory', 'Accessory'), ('amc', 'AMC')], default='drone', max_length=20),
        ),
    ]
