# Generated by Django 5.2.2 on 2025-07-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0052_invoicedetails_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_app.paymentdetails'),
        ),
    ]
