# Generated by Django 5.2.2 on 2025-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0053_invoicedetails_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='serial_no',
            field=models.IntegerField(default=1),
        ),
    ]
