# Generated by Django 5.2.2 on 2025-07-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0054_invoicedetails_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
    ]
