# Generated by Django 5.2.2 on 2025-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0055_alter_invoicedetails_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='total_invoice_status',
            field=models.IntegerField(default=0),
        ),
    ]
