# Generated by Django 5.2.2 on 2025-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0056_invoicedetails_total_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='drone_model',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
