# Generated by Django 5.2.2 on 2025-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregister',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerregister',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerregister',
            name='otp_send_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerregister',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerregister',
            name='register_type',
            field=models.CharField(default='Manual', max_length=20),
        ),
    ]
