# Generated by Django 5.2.2 on 2025-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0010_kycdetails_idfy_pan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='aadhaar_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
