# Generated by Django 5.2.2 on 2025-06-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0025_customermoredetails_role_customerregister_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoredetails',
            name='selfie_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customermoredetails',
            name='signature_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
