# Generated by Django 5.2.2 on 2025-06-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0028_paymentdetails_admin_paymentdetails_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineedetails',
            name='nominee_status',
            field=models.IntegerField(default=0),
        ),
    ]
