# Generated by Django 5.2.2 on 2025-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0036_alter_paymentdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='drone_payment_status',
            field=models.CharField(default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
